version: '3.7'

services: 
    traktor-agent:
        build: ./traktoragent/
        ports: 
            - "13336:13336"
        networks: 
            - traktor_network
        environment: 
            AGENT_IP: 0.0.0.0
            AGENT_PORT: 13336
    traktor-registry:
        build: ./traktorregistry/
        ports:
            - "8090:8090"
        networks: 
            - traktor_network
        environment: 
            REGISTRY_PORT: 8090
    traktor-fibonacci-server:
        build: ./traktor-fibonacci-server/
        ports:
            - "8084:8084"
        environment: 
            REGISTRY_IP: "traktor-registry"
            REGISTRY_PORT: "8090"
            AGENT_IP: traktor-agent
            AGENT_PORT: 13336
            REPORTER_PORT: 13337
        depends_on:
            - traktor-agent
            - traktor-registry
        networks: 
            - traktor_network
    traktor-fibonacci-caller:
        #image: fibo-caller
        build: ./traktor-fibonacci-caller/
        build:
            context: ./traktor-fibonacci-caller/
            dockerfile: Dockerfile_interceptor
        ports:
            - "8085:8085"
        environment: 
            REGISTRY_IP: "traktor-registry"
            REGISTRY_PORT: "8090"
            AGENT_IP: traktor-agent
            AGENT_PORT: 13336
            REPORTER_PORT: 13338
            FIBO_IP: "traktor-fibonacci-server"
            FIBO_PORT: "8084"
        depends_on:
            - traktor-agent
            - traktor-registry
        networks: 
            - traktor_network
        cap_add:
            - NET_ADMIN
networks:
    traktor_network:
